// Generates TypeScript API types and a JSON Schema bundle from contracts/ (never edit the output by hand).
//
//   node scripts/gen-api.mjs          write src/api/generated/*
//   node scripts/gen-api.mjs --check  fail if src/api/generated/* is stale (used by `pnpm lint`)
//
// Cross-platform: pure Node.js, paths via node:path / node:url.
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import * as prettier from "prettier";

const here = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(here, "..");
const repoRoot = path.resolve(appRoot, "..", "..");
const contracts = path.join(repoRoot, "contracts");
const outDir = path.join(appRoot, "src", "api", "generated");

export const APIS = ["orchestrator", "registry", "storage", "llm", "handler", "assistant", "collector"];

const HEADER =
  "// GENERATED by web/admin/scripts/gen-api.mjs from contracts/ - do not edit.\n" + "/* eslint-disable */\n";

async function listSchemaFiles(dir, prefix = "") {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await listSchemaFiles(path.join(dir, entry.name), rel)));
    else if (entry.name.endsWith(".schema.json")) out.push(rel);
  }
  return out.sort();
}

async function format(source, filepath) {
  const options = (await prettier.resolveConfig(path.join(repoRoot, ".prettierrc.json"))) ?? {};
  return prettier.format(source, { ...options, filepath });
}

/**
 * openapi-typescript quirks with plain JSON Schema files referenced from OpenAPI:
 *  1. a nested `$defs` object becomes a (required) property of the object type - it is removed, the definitions
 *     are emitted as components anyway;
 *  2. `discriminator` without `mapping` injects `<prop>: "<SchemaName>"` - it is replaced by the `const` the
 *     schema really declares for that property (e.g. `type: "seed_list"`, `collector: "web"`).
 */
export function fixGenerated(source, consts) {
  const lines = source.split("\n");
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "$defs: {") {
      let depth = 0;
      for (; i < lines.length; i++) {
        for (const ch of lines[i]) {
          if (ch === "{") depth++;
          else if (ch === "}") depth--;
        }
        if (depth === 0) break;
      }
      continue;
    }
    out.push(line);
  }
  const text = out.join("\n");
  const marker =
    /(\n\s*\/\*\*\n\s*\* @description discriminator enum property added by openapi-typescript\n\s*\* @enum \{string\}\n\s*\*\/\n)(\s*)([A-Za-z_]+): "([A-Za-z0-9_]+)";/g;
  return text.replace(marker, (_all, _doc, indent, prop, name) => {
    const value = consts.get(`${name}.${prop}`);
    return value === undefined
      ? ""
      : `\n${indent}/** @constant */\n${indent}${prop}: ${JSON.stringify(value)};`;
  });
}

/** `<DefName>.<property>` -> const value, over every $defs entry of the contract schemas. */
function collectConsts(schemas) {
  const consts = new Map();
  for (const schema of Object.values(schemas)) {
    for (const [name, def] of Object.entries(schema.$defs ?? {})) {
      for (const [prop, spec] of Object.entries(def.properties ?? {})) {
        if (spec && Object.prototype.hasOwnProperty.call(spec, "const"))
          consts.set(`${name}.${prop}`, spec.const);
      }
    }
  }
  return consts;
}

async function generate() {
  // JSON Schemas of configuration documents: the admin validates editors against them (ajv 2020-12).
  const schemaDir = path.join(contracts, "schemas");
  const schemas = {};
  for (const rel of await listSchemaFiles(schemaDir)) {
    schemas[rel] = JSON.parse(await readFile(path.join(schemaDir, rel), "utf8"));
  }
  const consts = collectConsts(schemas);
  /** @type {Map<string, string>} */
  const files = new Map();
  for (const api of APIS) {
    const spec = pathToFileURL(path.join(contracts, "openapi", `${api}.v1.yaml`));
    const ast = await openapiTS(spec, {
      defaultNonNullable: false,
      alphabetize: false,
      emptyObjectsUnknown: true,
    });
    files.set(`${api}.ts`, HEADER + fixGenerated(astToString(ast), consts));
  }
  files.set(
    "schemas.ts",
    HEADER +
      "// Contract JSON Schemas keyed by their path under contracts/schemas/.\n" +
      `export const contractSchemas: Record<string, Record<string, unknown>> = ${JSON.stringify(schemas)};\n`,
  );
  const formatted = new Map();
  for (const [name, source] of files) formatted.set(name, await format(source, path.join(outDir, name)));
  return formatted;
}

async function main() {
  const check = process.argv.includes("--check");
  const files = await generate();
  if (check) {
    const stale = [];
    for (const [name, source] of files) {
      const target = path.join(outDir, name);
      const current = existsSync(target) ? await readFile(target, "utf8") : null;
      if (current !== source) stale.push(name);
    }
    if (stale.length) {
      console.error(`gen-api: stale generated files: ${stale.join(", ")} - run \`pnpm gen:api\``);
      process.exit(1);
    }
    console.log(`gen-api: ${files.size} generated files are up to date`);
    return;
  }
  await mkdir(outDir, { recursive: true });
  for (const [name, source] of files) await writeFile(path.join(outDir, name), source, "utf8");
  console.log(`gen-api: wrote ${files.size} files to ${path.relative(appRoot, outDir)}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
