"""Generate typed clients from OpenAPI contracts.

    uv run jane-codegen client contracts/<svc>/openapi.yaml --out services/<me>/src/<pkg>/_generated/<svc>

writes a package with
  * ``models.py`` - Pydantic v2 models of ``components/schemas`` (datamodel-code-generator);
  * ``client.py`` - ``<Name>Client(ServiceClient)`` with one async method per ``operationId``;
    responses whose schema is a ``$ref`` to a component are parsed into that model.

Generated code goes into ``_generated/`` directories, which ruff and mypy skip. Regenerate instead of
editing. CONNECTION POINT (WP-00): the contract locations are defined in ``contracts/``.
"""

from __future__ import annotations

import argparse
import importlib.util
import keyword
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from jane_kit.contracts import OpenAPISpec, Operation

__all__ = ["generate_client", "generate_client_source", "generate_models", "main"]

HEADER = "# Generated by jane-codegen from {src}. Do not edit; regenerate instead.\n"


def _snake(name: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z]+", "_", name)
    s = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", s).lower().strip("_")
    if not s or s[0].isdigit():
        s = f"op_{s}"
    return f"{s}_" if keyword.iskeyword(s) else s


def _class_name(name: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[^0-9a-zA-Z]+", name) if part) or "Service"


def _model_ref(spec: OpenAPISpec, op: Operation) -> str | None:
    """Component name of the first 2xx JSON response schema, if it is ``#/components/schemas/<X>`` of this spec."""
    responses = op.spec.get("responses") or {}
    for status in sorted(responses):
        if status.startswith("2"):
            resp = spec.follow(op.loc.child("responses", status))
            for media in (resp.node.get("content") or {}).values():
                ref = str((media.get("schema") or {}).get("$ref", ""))
                if resp.uri == spec.base_uri and ref.startswith("#/components/schemas/"):
                    return ref.rsplit("/", 1)[1]
            return None
    return None


def _operation_name(op: Operation) -> str:
    if op.operation_id:
        return _snake(op.operation_id)
    return _snake(f"{op.method}_{op.path}")


def generate_client_source(spec: OpenAPISpec, class_name: str, source: str, with_models: bool) -> str:
    lines = [
        HEADER.format(src=source),
        "from __future__ import annotations\n",
        "from typing import Any\n",
        "from jane_kit.clients import ServiceClient\n",
    ]
    if with_models:
        lines.append("from . import models\n")
    lines += ["", f"class {class_name}Client(ServiceClient):", f'    """Client for {source}."""', ""]
    used: set[str] = set()
    for op in spec.operations:
        name = _operation_name(op)
        while name in used:
            name += "_"
        used.add(name)
        params = list(op.parameters)
        path_params = [p["name"] for p in params if p.get("in") == "path"]
        query_params = [p["name"] for p in params if p.get("in") == "query"]
        args = ["self", *(f"{_snake(p)}: str" for p in path_params)]
        kw: list[str] = []
        if op.spec.get("requestBody") is not None:
            kw.append("body: Any = None")
        kw += [f"{_snake(q)}: Any = None" for q in query_params]
        if op.method not in {"GET", "HEAD"}:
            kw.append("idempotency_key: str | None = None")
        signature = ", ".join(args + (["*", *kw] if kw else []))
        model = _model_ref(spec, op) if with_models else None
        ret = f"models.{model}" if model else "Any"
        doc = (op.spec.get("summary") or f"{op.method} {op.path}").replace('"""', "'")
        path_expr = "f" + repr(re.sub(r"\{([^}]+)\}", lambda m: "{" + _snake(m.group(1)) + "}", op.path))
        lines.append(f"    async def {name}({signature}) -> {ret}:")
        lines.append(f'        """{doc}"""')
        if query_params:
            pairs = ", ".join(f"{q!r}: {_snake(q)}" for q in query_params)
            lines.append(f"        params = {{k: v for k, v in {{{pairs}}}.items() if v is not None}}")
        else:
            lines.append("        params = None")
        call = [f"{op.method!r}", path_expr, "params=params"]
        if op.spec.get("requestBody") is not None:
            call.append("json=body")
        if op.method not in {"GET", "HEAD"}:
            call.append("idempotency_key=idempotency_key")
        lines.append(f"        response = await self.request({', '.join(call)})")
        if model:
            lines.append(f"        return models.{model}.model_validate(response.json())")
        else:
            lines.append("        return response.json() if response.content else None")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_models(spec_path: Path, out_file: Path) -> None:
    """Pydantic v2 models via datamodel-code-generator (dev dependency; falls back to ``uvx``)."""
    args = [
        "--input",
        str(spec_path),
        "--input-file-type",
        "openapi",
        "--output",
        str(out_file),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--target-python-version",
        "3.12",
        "--use-standard-collections",
        "--use-union-operator",
        "--field-constraints",
        "--disable-timestamp",
        "--use-schema-description",
    ]
    if importlib.util.find_spec("datamodel_code_generator") is not None:
        cmd = [sys.executable, "-m", "datamodel_code_generator", *args]
    elif shutil.which("uvx"):
        cmd = ["uvx", "--from", "datamodel-code-generator", "datamodel-codegen", *args]
    else:
        raise RuntimeError("datamodel-code-generator is not installed and uvx is not available")
    subprocess.run(cmd, check=True)  # noqa: S603


def generate_client(
    spec_path: str | Path, out_dir: str | Path, class_name: str | None = None, with_models: bool = True
) -> Path:
    spec_path = Path(spec_path)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    spec = OpenAPISpec.load(spec_path)
    title: Any = (spec.document.get("info") or {}).get("title") or spec_path.parent.name
    name = class_name or _class_name(str(title))
    has_schemas = bool((spec.document.get("components") or {}).get("schemas"))
    with_models = with_models and has_schemas
    if with_models:
        generate_models(spec_path, out / "models.py")
    source = spec_path.as_posix()
    (out / "client.py").write_text(
        generate_client_source(spec, name, source, with_models), encoding="utf-8", newline="\n"
    )
    exports = [f"{name}Client"]
    init = HEADER.format(src=source) + f"from .client import {name}Client\n"
    if with_models:
        init += "from . import models\n"
        exports.append("models")
    init += f"\n__all__ = {exports!r}\n"
    (out / "__init__.py").write_text(init, encoding="utf-8", newline="\n")
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="jane-codegen", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("client", help="generate models + async client package from an OpenAPI 3.1 spec")
    c.add_argument("spec", type=Path)
    c.add_argument("--out", type=Path, required=True)
    c.add_argument("--class-name")
    c.add_argument("--no-models", action="store_true")
    m = sub.add_parser("models", help="generate only Pydantic models")
    m.add_argument("spec", type=Path)
    m.add_argument("--out", type=Path, required=True, help="output .py file")
    ns = parser.parse_args(argv)
    if ns.cmd == "client":
        out = generate_client(ns.spec, ns.out, ns.class_name, not ns.no_models)
        print(f"generated {out}")
    else:
        ns.out.parent.mkdir(parents=True, exist_ok=True)
        generate_models(ns.spec, ns.out)
        print(f"generated {ns.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
